version: '3.5'

services:
  app:
    build:
      context: .docker/php
    environment:
      - DATABASE_URL=mysql://root:123456@db:3306/app_db?serverVersion=5.7
    volumes:
      - ./app:/var/www/app
    networks:
      - app_net
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - .docker/database/dump:/sql
      - .docker/database/data:/var/lib/mysql
    networks:
      - app_net

  redis:
    image: redis:6.0-rc-alpine
    command: redis-server --requirepass 123456
    networks:
      - app_net
    depends_on:
      - db

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - ./app:/var/www/app:delegated
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites:/etc/nginx/sites-available
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - '8080:80'
    networks:
      - app_net
    depends_on:
      - app

networks:
  app_net:
